// $apply — aggregation, grouping, and pre-filtering.
//
// Spec source:
//   https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/query/aggregate-data
//
// Canonical pipeline shape (in order of execution):
//
//   $apply=filter(<predicate>)/groupby((<col>[, <col>]),aggregate(<agg>[, <agg>]))
//          └─ stage 1 ─────┘ └─ stage 2 ──────────┘ └─ stage 3 ───────────┘
//                                                    optional w/ groupby
//
// Or one of the degenerate forms:
//   $apply=aggregate(<agg>[, <agg>])                  → single-row aggregate
//   $apply=groupby((<col>[, <col>]))                  → distinct values
//   $apply=filter(<predicate>)/groupby((<col>))       → distinct values w/ pre-filter
//
// Per the doc, each <agg> takes one of these shapes:
//   <col> with sum     as <alias>
//   <col> with average as <alias>
//   <col> with min     as <alias>
//   <col> with max     as <alias>
//   $count as <alias>    ← row count — pseudo-column, no "with"
//
// Per the "OData aggregation limitations" section:
//   • countdistinct (CountColumn in FetchXml) is NOT supported in OData.
//   • $orderby with aggregate values is not supported.
//   • groupby on DateTime is not supported.
//   • Hard 50,000-row cap on the input set.
//
// Pre-filter lives inside the pipeline as
// `filter(<predicate>)`. The predicate is the same OData $filter expression
// shape used by the top-level $filter — so we reuse the existing FilterEditor
// component for the editing surface. Encoding is delegated to
// `groupToOData(prefilter, table)`.

import { useMemo } from 'react';
import {
  Button, Combobox, Input, Option, tokens, Caption1, Badge, Switch,
  MessageBar, MessageBarBody, MessageBarTitle, mergeClasses,
} from '@fluentui/react-components';
import { Add20Regular, Delete20Regular, ChartMultiple20Filled, Filter20Filled } from '@fluentui/react-icons';
import { useStudioStyles } from '../primitives/styles';
import { findTable } from '../mock/metadata';
import { NavPathColumnPicker } from '../primitives/NavPathColumnPicker';
import { SortableList, SortableItem } from '../primitives/Sortable';
import { PaneHead } from './PaneHead';
import { FilterEditor } from './filter/FilterEditor';
import { emptyTree, groupToOData, type FilterGroup } from './filter/filterTree';
import type { RequestGroup } from '../registry/requestTypes';

// ── Types ──────────────────────────────────────────────────────────────────

/**
 * Aggregate function. `$count` is the pseudo-aggregate (no source column
 * required) that emits `$count as <alias>` per the doc's "Count by status"
 * example.
 *
 * Note: `countdistinct` from prior versions of this state shape was a v2.2
 * artboard concept that mirrored the FetchXml `CountColumn`. It is NOT a
 * supported OData aggregate. We migrate any legacy `countdistinct` to
 * `$count` (with a runtime advisory) so existing saved queries don't break.
 */
export type AggFn = 'sum' | 'average' | 'min' | 'max' | '$count';

export interface ApplyAgg {
  /** Stable id for keying / DnD reorder. Generated by `addAgg`; older
   *  persisted state without an id falls back to alias-or-index keying. */
  id?: string;
  /**
   * Source column for the aggregate. For `$count` this is ignored and emitted
   * as the literal `$count` pseudo-column. Lookup paths (e.g.
   * `primarycontactid/fullname`) are allowed — Dataverse evaluates them
   * through the FK join.
   */
  col: string;
  fn: AggFn;
  /** Output alias — required by the OData spec. */
  alias: string;
}

export interface ApplySpec {
  enabled: boolean;
  /**
   * Pre-filter — runs BEFORE groupby/aggregate. Reuses the same FilterGroup
   * shape as the top-level $filter. Empty group ({ rules: [] }) → no filter
   * stage emitted.
   */
  prefilter: FilterGroup;
  /**
   * Group-by columns. Lookup paths (`primarycontactid/fullname`) are
   * permitted per the docs. Empty array → no groupby stage; aggregate alone
   * returns one row.
   */
  groupby: string[];
  /** Aggregate list. Empty → no aggregate stage; groupby alone returns distinct rows. */
  aggregates: ApplyAgg[];
}

export const emptyApply = (): ApplySpec => ({
  enabled: false,
  prefilter: emptyTree(),
  groupby: [],
  aggregates: [],
});

// ── Helpers — aggregatable / groupable column predicates ───────────────────

function isNumeric(c: { attributeType: string }) {
  return c.attributeType === 'Integer' || c.attributeType === 'BigInt' ||
         c.attributeType === 'Decimal' || c.attributeType === 'Double' ||
         c.attributeType === 'Money';
}

function isDateLike(c: { attributeType: string }) {
  return c.attributeType === 'DateTime';
}

/**
 * Per-function column eligibility. Sourced from the aggregate-data doc's
 * examples + OData type system:
 *
 *   sum     → numeric only. Summing a date or string is nonsensical and
 *             Dataverse rejects it.
 *   average → numeric only. Same reasoning as sum.
 *   min     → numeric OR DateTime. The doc's "First created record" example
 *             uses `createdon with min as firstCreate`.
 *   max     → numeric OR DateTime. The doc's "Last created record" example
 *             uses `createdon with max as lastCreate`.
 *   $count  → no source column (returns the row count).
 *
 * This filters the column picker so the user can't pick an invalid pair.
 */
export function isAggregateEligible(fn: AggFn, c: { attributeType: string }): boolean {
  switch (fn) {
    case 'sum':
    case 'average':
      return isNumeric(c);
    case 'min':
    case 'max':
      return isNumeric(c) || isDateLike(c);
    case '$count':
      return false; // $count has no source column
  }
}

// ── Editor ─────────────────────────────────────────────────────────────────

export function ApplyEditor({ table, spec, setSpec, group = 'read' }: {
  table: string;
  spec: ApplySpec;
  setSpec: (s: ApplySpec) => void;
  group?: RequestGroup;
}) {
  const s = useStudioStyles();
  const tbl = findTable(table);

  // ── Column filters ──
  // groupby: per doc, DateTime is NOT supported. Memo / File / Image excluded
  //   because aggregating large blobs is meaningless server-side.
  const groupableCols = useMemo(() => tbl
    ? tbl.columns.filter(c =>
        c.attributeType !== 'DateTime' && c.attributeType !== 'Memo' &&
        c.attributeType !== 'File' && c.attributeType !== 'Image',
      )
    : [], [tbl]);

  // Per-function eligibility — derive once per render. The picker for each
  // aggregate row reads `colsFor(a.fn)` to scope choices.
  const colsFor = useMemo(() => (fn: AggFn) => tbl
    ? tbl.columns.filter(c => isAggregateEligible(fn, c))
    : [], [tbl]);
  // Default seed for "Add scalar aggregate" — numeric columns are the safest
  // starting point.
  const numericCols = useMemo(() => tbl ? tbl.columns.filter(isNumeric) : [], [tbl]);

  if (!tbl) return null;

  // ── Mutators ──
  // Switch fires (ev, { checked }); read the data shape so we set state to the
  // explicit value rather than toggling. This avoids race-conditions when the
  // Switch is rapidly toggled.
  const toggle = (_: unknown, d: { checked: boolean }) =>
    setSpec({ ...spec, enabled: !!d.checked });
  const setPrefilter = (f: FilterGroup) => setSpec({ ...spec, prefilter: f });

  const addGroup = (col: string) => setSpec({ ...spec, groupby: [...spec.groupby, col] });
  const rmGroup  = (i: number)   => setSpec({ ...spec, groupby: spec.groupby.filter((_, j) => j !== i) });

  const newAggId = () =>
    (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function')
      ? `agg_${crypto.randomUUID()}`
      : `agg_${Date.now().toString(36)}_${Math.floor(Math.random() * 1e6).toString(36)}`;

  const addAgg = (fn: AggFn) => {
    if (fn === '$count') {
      setSpec({
        ...spec,
        aggregates: [...spec.aggregates, { id: newAggId(), col: '$count', fn: '$count', alias: 'count' }],
      });
      return;
    }
    // Seed with the first column eligible for this fn (numeric for sum/avg,
    // numeric-or-date for min/max).
    const c = colsFor(fn)[0];
    if (!c) return;
    setSpec({
      ...spec,
      aggregates: [...spec.aggregates, { id: newAggId(), col: c.logicalName, fn, alias: `${c.logicalName}_${fn}` }],
    });
  };
  const updAgg = (i: number, p: Partial<ApplyAgg>) =>
    setSpec({ ...spec, aggregates: spec.aggregates.map((a, j) => j === i ? { ...a, ...p } : a) });
  const rmAgg  = (i: number) =>
    setSpec({ ...spec, aggregates: spec.aggregates.filter((_, j) => j !== i) });

  // ── Pipeline preview — built from the encoder so the user sees the
  //    actual wire format and not a hand-pretty-printed version. ──
  const pipelinePreview = useMemo(() => applyToOData(spec, tbl) || '(empty)', [spec, tbl]);

  // Stable ids for the aggregate row DnD. Legacy persisted aggregates may
  // lack an `id` — fall back to a positional-but-stable token. Memo keyed
  // on the spec.aggregates length+content so we don't churn ids each render.
  const aggIds = useMemo(
    () => spec.aggregates.map((a, i) => a.id ?? `__agg_${i}__`),
    [spec.aggregates],
  );

  // ── Render ──
  return (
    <div>
      <PaneHead
        icon={ChartMultiple20Filled}
        title="$apply"
        sub="Aggregate, group, and pre-filter server-side. Capped at 50,000 input rows; groupby on DateTime not supported."
        group={group}
      >
        {/* Switch reads as a binary on/off control. The earlier primary Button
            looked like a CTA — the user expected "Enabled" to act like Submit. */}
        <Switch
          checked={spec.enabled}
          onChange={toggle}
          label={spec.enabled ? 'On' : 'Off'}
          labelPosition="before"
        />
      </PaneHead>

      {!spec.enabled && (
        <MessageBar layout="multiline" intent="info" style={{ marginBottom: 12 }}>
          <MessageBarBody>
            <code>$apply</code> is disabled — toggle it on to compose a{' '}
            <code>filter(…)/groupby(…)/aggregate(…)</code> pipeline.
          </MessageBarBody>
        </MessageBar>
      )}

      {spec.enabled && (
        <MessageBar layout="multiline" intent="warning" style={{ marginBottom: 12 }}>
          <MessageBarBody>
            <MessageBarTitle>$apply replaces most other query options.</MessageBarTitle>
            Per the Dataverse <em>aggregate-data</em> docs, when <code>$apply</code> is set the following are <strong>not applied</strong>:
            <ul style={{ margin: '6px 0 6px 18px', padding: 0 }}>
              <li><code>$select</code> — output columns come from groupby + aggregate aliases</li>
              <li><code>$filter</code> — use the <strong>filter() stage below</strong> instead</li>
              <li><code>$orderby</code> — sorting aggregate output isn't supported</li>
              <li><code>$expand</code> — joins aren't allowed alongside aggregation</li>
              <li><code>$count</code> — use <code>$count as &lt;alias&gt;</code> inside aggregate() instead</li>
            </ul>
            Only <code>$top</code> still works alongside <code>$apply</code>. <strong>50,000-row hard cap</strong> on the input set.
          </MessageBarBody>
        </MessageBar>
      )}

      {/* Pipeline preview chip — shows the composed $apply= string. */}
      {spec.enabled && (
        <div className={mergeClasses(s.inlineCard)} style={{
          padding: '8px 12px',
          marginBottom: 14,
          maxWidth: 980,
        }}>
          <Caption1 style={{ fontWeight: 600, color: tokens.colorNeutralForeground2, display: 'block', marginBottom: 4 }}>
            Pipeline preview
          </Caption1>
          <code style={{
            fontFamily: tokens.fontFamilyMonospace,
            fontSize: 11,
            color: tokens.colorBrandForeground1,
            wordBreak: 'break-all',
          }}>
            $apply={pipelinePreview}
          </code>
        </div>
      )}

      <div style={{
        display: 'flex', flexDirection: 'column', gap: 22,
        opacity: spec.enabled ? 1 : 0.45,
        pointerEvents: spec.enabled ? 'auto' : 'none',
      }}>
        {/* ── Stage 1: filter() ─────────────────────────────────── */}
        <PipelineStage
          n={1}
          icon={<Filter20Filled style={{ color: tokens.colorBrandForeground1 }} />}
          title="filter(…)"
          hint="Pre-filter the source set before grouping/aggregating. Same syntax as $filter — runs first in the pipeline."
        >
          {/* Reuses FilterEditor but in a compact mode (no PaneHead — the
              stage header already wraps the section). */}
          <FilterEditor
            table={table}
            tree={spec.prefilter}
            setTree={setPrefilter}
            group={group}
            compact
          />
        </PipelineStage>

        {/* ── Stage 2: groupby() ────────────────────────────────── */}
        <PipelineStage
          n={2}
          icon={<ChartMultiple20Filled style={{ color: tokens.colorBrandForeground1 }} />}
          title="groupby((…))"
          hint="Group by one or more columns. Drill INTO a lookup (e.g. primarycontactid → fullname) — Dataverse rejects bare lookups and `_<attr>_value` forms. DateTime columns are not supported."
        >
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 8 }}>
            {spec.groupby.length === 0 && (
              <Caption1 style={{ color: tokens.colorNeutralForeground3, fontStyle: 'italic' }}>
                No grouping — aggregate() will return a single summary row.
              </Caption1>
            )}
            {/* Chips are horizontally laid out and drag-reorderable. The
                chip itself is the drag handle — no separate grip needed
                (chip-style elements ARE the gripper). Click the trash icon
                to remove; drag anywhere else on the chip to reorder. */}
            <SortableList
              ids={spec.groupby}
              orientation="horizontal"
              onReorder={(from, to) => {
                const next = [...spec.groupby];
                const [moved] = next.splice(from, 1);
                next.splice(to, 0, moved);
                setSpec({ ...spec, groupby: next });
              }}
            >
              {spec.groupby.map((g, i) => {
                const leaf = g.split('/').pop() ?? g;
                const c = tbl.columns.find(x => x.logicalName === leaf);
                const display = g.includes('/') ? g : (c?.displayName ?? g);
                return (
                  <SortableItem key={g} id={g}>
                    {({ gripProps, Grip }) => (
                      <Badge
                        appearance="tint"
                        color="brand"
                        style={{ paddingRight: 0, gap: 4 }}
                      >
                        <span {...gripProps} aria-label={`Drag to reorder ${display}`} style={{ display: 'inline-flex', ...gripProps.style }}>
                          <Grip />
                        </span>
                        <span style={{ fontFamily: tokens.fontFamilyMonospace, fontSize: 11 }}>
                          {display}
                        </span>
                        <Button
                          icon={<Delete20Regular style={{ width: 12, height: 12 }} />}
                          size="small"
                          appearance="subtle"
                          onClick={() => rmGroup(i)}
                          aria-label={`Remove ${g}`}
                        />
                      </Badge>
                    )}
                  </SortableItem>
                );
              })}
            </SortableList>
          </div>
          {/* Nav-path-aware picker. Spec: `groupby((primarycontactid/fullname))`
              is supported (/webapi/query/aggregate-data §Total account
              revenue by primary contact name; empirically test 10.7 / 13.18).
              Excluded as leaves:
                • DateTime — groupby on DateTime not supported (test 10.8)
                • Memo / File / Image — meaningless aggregations
                • Lookup / Customer / Owner — BOTH the bare-lookup form
                  (test 10.6b) AND the `_<attr>_value` form (test 10.6)
                  are rejected. The user must drill INTO the lookup to a
                  scalar attribute on the related table. NavPathColumnPicker
                  still treats lookups as drill-in points, so the path is
                  reachable through the picker — just not selectable as a
                  leaf on its own. */}
          <NavPathColumnPicker
            rootTable={table}
            value=""
            onChange={(path) => {
              if (path && !spec.groupby.includes(path)) addGroup(path);
            }}
            leafFilter={(c) =>
              c.attributeType !== 'DateTime' &&
              c.attributeType !== 'Memo' &&
              c.attributeType !== 'File' &&
              c.attributeType !== 'Image' &&
              c.attributeType !== 'Lookup' &&
              c.attributeType !== 'Customer' &&
              c.attributeType !== 'Owner' &&
              !spec.groupby.includes(c.logicalName)
            }
            placeholder="Add a group-by column or path…"
          />
        </PipelineStage>

        {/* ── Stage 3: aggregate() ──────────────────────────────── */}
        <PipelineStage
          n={3}
          icon={<ChartMultiple20Filled style={{ color: tokens.colorBrandForeground1 }} />}
          title="aggregate(…)"
          hint="Compute per-group totals (when groupby is set) or single-row totals (when it isn't). $count is the row-count pseudo-aggregate."
        >
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            <SortableList
              ids={aggIds}
              onReorder={(from, to) => {
                const next = [...spec.aggregates];
                const [moved] = next.splice(from, 1);
                next.splice(to, 0, moved);
                setSpec({ ...spec, aggregates: next });
              }}
            >
            {spec.aggregates.map((a, i) => {
              const eligibleCols = colsFor(a.fn);
              const colMissing = a.fn !== '$count' && !eligibleCols.some(c => c.logicalName === a.col);
              const aggId = aggIds[i];
              return (
              <SortableItem key={aggId} id={aggId}>
                {({ gripProps, Grip }) => (
                <div
                  className={mergeClasses(s.inlineCard)}
                  style={{
                    padding: '10px 12px',
                    display: 'flex',
                    flexWrap: 'wrap',
                    gap: 10,
                    alignItems: 'center',
                  }}
                >
                  <span {...gripProps} aria-label="Drag to reorder aggregate">
                    <Grip />
                  </span>
                  {/* Field labels live above each input so cramped widths don't
                      collide. fn-picker comes first because it gates the column
                      list (numeric vs numeric+date). */}
                  <LabeledInput label="function" minWidth={140}>
                    <Combobox
                      size="small"
                      value={a.fn}
                      selectedOptions={[a.fn]}
                      onOptionSelect={(_, d) => {
                        if (!d.optionValue) return;
                        const fn = d.optionValue as AggFn;
                        if (fn === '$count') {
                          updAgg(i, { fn, col: '$count', alias: a.alias === '' ? 'count' : a.alias });
                          return;
                        }
                        // Reset col to the first one eligible for the new fn if the
                        // current pick isn't valid (e.g. switching avg → max keeps
                        // numeric; switching sum → min from datetime needs reset).
                        const eligibleForNewFn = tbl.columns.filter(c => isAggregateEligible(fn, c));
                        const stillValid = eligibleForNewFn.some(c => c.logicalName === a.col);
                        const col = stillValid
                          ? a.col
                          : (eligibleForNewFn[0]?.logicalName ?? '');
                        updAgg(i, { fn, col, alias: `${col}_${fn}` });
                      }}
                      style={{ minWidth: 140 }}
                    >
                      <Option value="sum">sum</Option>
                      <Option value="average">average</Option>
                      <Option value="min">min</Option>
                      <Option value="max">max</Option>
                      <Option value="$count">$count</Option>
                    </Combobox>
                  </LabeledInput>

                  {/* Column — hidden for $count, otherwise scoped by fn. */}
                  {a.fn !== '$count' && (
                    <LabeledInput label="column" minWidth={220} grow>
                      <Combobox
                        size="small"
                        value={tbl.columns.find(c => c.logicalName === a.col)?.displayName ?? a.col}
                        selectedOptions={[a.col]}
                        onOptionSelect={(_, d) => d.optionValue && updAgg(i, {
                          col: d.optionValue,
                          alias: `${d.optionValue}_${a.fn}`,
                        })}
                        style={{ minWidth: 220, width: '100%' }}
                      >
                        {eligibleCols.map(c => (
                          <Option key={c.logicalName} value={c.logicalName} text={c.displayName}>
                            {c.displayName}{' '}
                            <span style={{ color: tokens.colorNeutralForeground3, fontFamily: tokens.fontFamilyMonospace, fontSize: 10 }}>
                              · {c.attributeType}
                            </span>
                          </Option>
                        ))}
                      </Combobox>
                    </LabeledInput>
                  )}

                  {/* Alias */}
                  <LabeledInput label="alias" minWidth={180} grow>
                    <Input
                      size="small"
                      value={a.alias}
                      onChange={(_, d) => updAgg(i, { alias: d.value })}
                      placeholder="alias"
                      style={{ fontFamily: tokens.fontFamilyMonospace, width: '100%' }}
                    />
                  </LabeledInput>

                  <Button
                    size="small"
                    appearance="subtle"
                    icon={<Delete20Regular />}
                    onClick={() => rmAgg(i)}
                    aria-label="Remove aggregate"
                    style={{ alignSelf: 'flex-end', marginBottom: 1 }}
                  />

                  {/* Inline validation — the per-fn eligibility filter means
                      switching to a stricter fn can leave a leftover column
                      that's now invalid. Surface it loudly. */}
                  {colMissing && (
                    <MessageBar layout="multiline" intent="warning" style={{ width: '100%' }}>
                      <MessageBarBody>
                        <code>{a.col}</code> isn't valid for <code>{a.fn}</code> — pick a {a.fn === 'sum' || a.fn === 'average' ? 'numeric' : 'numeric or DateTime'} column.
                      </MessageBarBody>
                    </MessageBar>
                  )}
                </div>
                )}
              </SortableItem>
              );
            })}
            </SortableList>
          </div>

          {/* Add-aggregate buttons — separate paths for $count vs scalar. */}
          <div style={{ marginTop: 10, display: 'flex', gap: 8 }}>
            <Button
              icon={<Add20Regular />}
              appearance="outline"
              size="small"
              onClick={() => addAgg('sum')}
              disabled={numericCols.length === 0}
            >
              Add scalar aggregate
            </Button>
            <Button
              icon={<Add20Regular />}
              appearance="outline"
              size="small"
              onClick={() => addAgg('$count')}
            >
              Add $count
            </Button>
          </div>
        </PipelineStage>
      </div>
    </div>
  );
}

// ── PipelineStage — visual wrapper for each $apply pipeline stage ──────────
// Numbered chip + icon + title + hint copy. Matches the v2.2 artboard's
// "labeled section with caption" pattern used elsewhere (e.g. ExpandOverview,
// BypassEditor sections).
function PipelineStage({
  n, icon, title, hint, children,
}: {
  n: number;
  icon: React.ReactNode;
  title: string;
  hint: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
        <Badge appearance="filled" color="brand" size="small" style={{ minWidth: 18, fontWeight: 700 }}>
          {n}
        </Badge>
        {icon}
        <code style={{
          fontFamily: tokens.fontFamilyMonospace, fontSize: 13, fontWeight: 600,
          color: tokens.colorNeutralForeground1,
        }}>
          {title}
        </code>
      </div>
      <Caption1 style={{ display: 'block', marginBottom: 10, color: tokens.colorNeutralForeground3 }}>
        {hint}
      </Caption1>
      {children}
    </section>
  );
}

// ── LabeledInput — micro-helper for the aggregate row ─────────────────────
// Caption above the field so labels don't collide with placeholder text on
// narrow viewports. `grow` lets the column / alias slots take leftover width.
function LabeledInput({
  label, minWidth, grow, children,
}: {
  label: string;
  minWidth: number;
  grow?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div style={{
      display: 'flex', flexDirection: 'column', gap: 2,
      minWidth, flexGrow: grow ? 1 : 0, flexShrink: 1,
    }}>
      <Caption1 style={{
        fontSize: 10, fontWeight: 600, letterSpacing: '0.3px',
        color: tokens.colorNeutralForeground3, textTransform: 'uppercase',
      }}>
        {label}
      </Caption1>
      {children}
    </div>
  );
}

// ── Encoder ────────────────────────────────────────────────────────────────

/**
 * Compose the on-wire `$apply=...` value (without the `$apply=` prefix).
 *
 * Output shape per the official doc:
 *   filter(<expr>)/groupby((<cols>),aggregate(<aggs>))
 *
 * Degenerate forms collapse naturally — when a stage is empty, it and its
 * separating slash are omitted.
 */
export function applyToOData(spec: ApplySpec, tbl?: import('../mock/metadata').TableMeta): string {
  if (!spec.enabled) return '';

  const stages: string[] = [];

  // Stage 1: filter()
  if (spec.prefilter && spec.prefilter.rules.length > 0 && tbl) {
    const f = groupToOData(spec.prefilter, tbl);
    if (f) stages.push(`filter(${f})`);
  }

  // Stage 2 + 3: groupby(...) and/or aggregate(...)
  //   - groupby + aggregate → groupby((cols),aggregate(aggs))
  //   - groupby alone       → groupby((cols))                       (distinct values)
  //   - aggregate alone     → aggregate(aggs)                       (single-row total)
  const aggParts = spec.aggregates
    .filter(a => a.alias.trim() !== '' && (a.fn === '$count' || a.col.trim() !== ''))
    .map(a => a.fn === '$count'
      ? `$count as ${a.alias}`
      : `${a.col} with ${a.fn} as ${a.alias}`);

  if (spec.groupby.length > 0) {
    const aggStage = aggParts.length ? `aggregate(${aggParts.join(',')})` : '';
    stages.push(aggStage
      ? `groupby((${spec.groupby.join(',')}),${aggStage})`
      : `groupby((${spec.groupby.join(',')}))`);
  } else if (aggParts.length > 0) {
    stages.push(`aggregate(${aggParts.join(',')})`);
  }

  return stages.join('/');
}
